// src/evidence.ts — hardcoded evidence dataset from PROCORE_CUSTOMER_EVIDENCE_V1.md
// DUPLICATE rows are excluded; only unique evidence rows are loaded.

import type { EvidenceRow } from './types.js';
import { EvidenceConfidence } from './types.js';

export const EVIDENCE_ROWS: EvidenceRow[] = [
  {
    evidence_id: 'REDDIT-001',
    confidence: EvidenceConfidence.OBSERVATION,
    acvType: 'unknown',
    rate_per_1m: 1000,
    renewal_increase_pct: 10.4,
    prev_rate_per_1m: 500,
    products: ['Project Management Pro', 'Quality & Safety'],
    note: 'Typical renewal 2–5%; this renewal 10.4%. No total ACV or annual invoice. Rate doubled despite downgrade.',
    source_url: 'https://www.reddit.com/r/Construction/comments/199uliq/procore_renewal_costs_escalating/',
  },
  {
    evidence_id: 'REDDIT-002',
    confidence: EvidenceConfidence.OBSERVATION,
    acvType: 'unknown',
    renewal_increase_pct: 150,
    note: 'Single case: 150% price jump after five years; described as non-negotiable. Do not generalize.',
    source_url: 'https://www.reddit.com/r/Construction/comments/199uliq/procore_renewal_costs_escalating/',
  },
  {
    evidence_id: 'REDDIT-003',
    confidence: EvidenceConfidence.OBSERVATION,
    acvType: 'unknown',
    annual_cost_usd: 30000,
    note: 'Range $30k–$60k; cannot derive ACV or savings.',
    source_url: 'https://www.reddit.com/r/Construction/comments/199uliq/procore_renewal_costs_escalating/',
  },
  {
    evidence_id: 'REDDIT-004',
    confidence: EvidenceConfidence.OBSERVATION,
    acvType: 'company',
    acv_usd: 200_000_000,
    annual_cost_usd: 385_000,
    rate_per_1m: 1925,
    contract_term: 'multi_year',
    note: 'Pass-through cost-recovery strategy; not evidence of a Procore discount.',
    source_url: 'https://www.reddit.com/r/ConstructionManagers/comments/1j1188g/procore_renewal/',
  },
  {
    evidence_id: 'REDDIT-005',
    confidence: EvidenceConfidence.OBSERVATION,
    acvType: 'company',
    acv_usd: 15_000_000,
    rate_per_1m: 1000,
    note: '$1k/$1M used for pass-through allocation, not necessarily the actual Procore invoice rate.',
    source_url: 'https://www.reddit.com/r/ConstructionManagers/comments/1j1188g/procore_renewal/',
  },
  {
    evidence_id: 'REDDIT-006',
    confidence: EvidenceConfidence.OBSERVATION,
    acvType: 'unknown',
    products: ['Submittals', 'RFIs', 'Change Orders', 'Inspections'],
    note: 'Fit/demand evidence only; does not establish commercial removability of a module.',
    source_url: 'https://www.reddit.com/r/Construction/comments/ack53j/anyone_know_what_they_pay_for_procore/',
  },
  {
    evidence_id: 'REDDIT-007',
    confidence: EvidenceConfidence.OBSERVATION,
    acvType: 'project',
    acv_usd: 15_000_000,
    annual_cost_usd: 20_000,
    rate_per_1m: 1333.33,
    note: 'Source says "$15M job", not company ACV. Project-level observation; do not use as company-ACV benchmark.',
    source_url: 'https://www.reddit.com/r/Construction/comments/ack53j/anyone_know_what_they_pay_for_procore/',
  },
  {
    evidence_id: 'REDDIT-008',
    confidence: EvidenceConfidence.OBSERVATION,
    acvType: 'company',
    acv_usd: 4_000_000,
    annual_cost_usd: 6_000,
    rate_per_1m: 1500,
    products: ['Project Management', 'Financial Management'],
    contract_term: 'annual',
    note: 'Annual cost from $500/month PM quote only; Financial is excluded (range estimate).',
    source_url: 'https://www.reddit.com/r/Construction/comments/1iqb442/construction_software_pricing_comparison_based_on/',
  },
  {
    evidence_id: 'REDDIT-009',
    confidence: EvidenceConfidence.OBSERVATION,
    acvType: 'unknown',
    contract_term: 'annual',
    note: 'Process observation only; does not establish pricing algorithm.',
    source_url: 'https://www.reddit.com/r/Construction/comments/10gh7ej',
  },
  {
    evidence_id: 'REDDIT-010',
    confidence: EvidenceConfidence.OBSERVATION,
    acvType: 'unknown',
    contract_term: 'multi_year',
    note: 'Pain/alternative evidence; not a pricing benchmark.',
    source_url: 'https://www.reddit.com/r/ConstructionManagers/comments/1j1188g/procore_renewal/',
  },
  {
    evidence_id: 'WEB-011',
    confidence: EvidenceConfidence.OBSERVATION,
    acvType: 'company',
    acv_usd: 400_000_000,
    annual_cost_usd: 324_000,
    rate_per_1m: 810,
    contract_term: 'multi_year',
    note: 'Annualized from $27k/month. Distinct from REDDIT-004; do not infer identical product bundles.',
    source_url: 'https://www.reddit.com/r/Construction/comments/1iqb442/construction_software_pricing_comparison_based_on/',
  },
  {
    evidence_id: 'WEB-014',
    confidence: EvidenceConfidence.BENCHMARK,
    acvType: 'project',
    acv_usd: 59_000_000,
    annual_cost_usd: 80_000,
    rate_per_1m: 1355.93,
    products: ['Project Management'],
    note: 'Secondary source; Financial module explicitly excluded. Not independently verified primary post.',
    source_url: 'https://downtobid.com/blog/how-much-is-procore-software',
  },
  {
    evidence_id: 'WEB-015',
    confidence: EvidenceConfidence.BENCHMARK,
    acvType: 'company',
    acv_usd: 55_000_000,
    annual_cost_usd: 55_000,
    rate_per_1m: 1000,
    note: 'Secondary source; do not count as new independent customer.',
    source_url: 'https://www.getonecrew.com/post/procore-reviews',
  },
  {
    evidence_id: 'WEB-016',
    confidence: EvidenceConfidence.VERIFIED_PUBLIC_DOCUMENT,
    acvType: 'project',
    acv_usd: 85_000_000,
    annual_cost_usd: 85_000,
    rate_per_1m: 1000,
    contract_term: 'annual',
    products: ['Procore CMIS'],
    note: 'Project-specific license; year-1 estimate. Not a standard commercial customer contract.',
    source_url: 'https://mccmeetings.blob.core.usgovcloudapi.net/escondidca-pubu/MEET-Packet-1c066802b58043ba9504a911b624394f.pdf',
  },
  {
    evidence_id: 'WEB-017',
    confidence: EvidenceConfidence.OBSERVATION,
    acvType: 'project',
    acv_usd: 4_000_000,
    annual_cost_usd: 7_500,
    rate_per_1m: 1875,
    products: ['Project Management Pro'],
    note: 'Older 2021 observation; source says "project revenue" not explicit ACV.',
    source_url: 'https://www.reddit.com/r/Construction/comments/lvpcvg',
  },
  {
    evidence_id: 'WEB-018',
    confidence: EvidenceConfidence.OBSERVATION,
    acvType: 'company',
    acv_usd: 10_000_000,
    annual_cost_usd: 10_000,
    rate_per_1m: 1000,
    products: ['PM Starter'],
    note: '$10k/year for PM Starter at $10–15M revenue; full-package ~$35k retained in notes only.',
    source_url: 'https://www.reddit.com/r/Construction/comments/oghlhi/any_of_you_specialty_subs_use_procore_if_so_how/',
  },
  {
    evidence_id: 'WEB-019',
    confidence: EvidenceConfidence.OBSERVATION,
    acvType: 'company',
    acv_usd: 20_000_000,
    annual_cost_usd: 40_000,
    rate_per_1m: 2000,
    note: 'Source says >$20M; $20M is a conservative normalization, not an exact rate.',
    source_url: 'https://www.reddit.com/r/ConstructionManagers/comments/1bvtinw/procore_capabilities/',
  },
  {
    evidence_id: 'WEB-021',
    confidence: EvidenceConfidence.OBSERVATION,
    acvType: 'company',
    acv_usd: 25_000_000,
    note: 'No quote; demand/negotiation evidence only.',
    source_url: 'https://www.reddit.com/r/Construction/comments/1nr3j7q/procore_for_small_commercial_gc/',
  },
  {
    evidence_id: 'WEB-022',
    confidence: EvidenceConfidence.OBSERVATION,
    acvType: 'unknown',
    products: ['Analytics', 'BIM', 'PM'],
    note: 'Qualitative renewal pain signal; does not prove removability or savings.',
    source_url: 'https://cafe.cfma.org/discussion/procore-renewals-requiring-wip-financial-statements-1',
  },
];

export function getUniqueRateRows(): EvidenceRow[] {
  return EVIDENCE_ROWS.filter(
    (r) => r.rate_per_1m !== undefined && r.confidence !== EvidenceConfidence.DUPLICATE,
  );
}
